* 2017
** 2017-11 November
*** 2017-11-24 Friday

**** journal means travel diary or a plan? 
It is my fourth day from my learning spacemacs.I'm willing to finish this journal to record the my excellent mood.
The config of my spacemacs is due to zilongshanren.And i am hungry to config the spacemacs by myself in the future.
And this all for today's journal.
*** 2017-11-26 Sunday

**** summary after reinstall ubuntu16.04 
It is me who get myself in the trouble.I want to change my desktop to gnome in place of unity yesterday.I find it's very uncomfortable to
use gnome,so i decide to uninstall gnome desktop.To be honest,i want to purge all application about gnome.After i finish that,i find i can
start many applications such as uget,chrome.What's more,the icons in the bottom bar also disappeared quietly.All happned scared me,however
i don't how to solve this problem.So i have to reinstall all applications back.Then i reboot,but i can't log in my system anymore.Saddly,i
have to make a hard decision that is to reinstall ubuntu16.
*** 2017-11-27 Monday

**** I find a great application which is free and quick vpn.It is lantern.But the version 
i download from web is for ubuntu14,it's amazing to me that the version is valid in ubuntu16.
Althougth it just provides user with 500 M/month,it's is enough for me,emmmmm,this month.
*** 2017-11-29 Wednesday

**** start learn emacs lisp.And i have finished to 1.1:Lisp List.
** 2017-12 December
*** 2017-12-05 Tuesday

**** 正如你所看到的哈哈，今天贼鸡儿开心，因为终于知道怎么在神之编辑器中输入中文了，喂，好像哪里不对劲。
这逗号好像飘了。。。。还有句号。。。。算了管不了那么多了，哈哈哈，开心！！！
*** 2017-12-06 Wednesday

**** 学会在 emacs 下输入中文的第二天 
  感觉依然兴奋，依然开心。经过一番简单的测试，在emacs中启用外置搜狗输入法，虽然标点符号的显示位置有些问题，但基
本不影响日常使用。这个对我来说可以说是一个神技，意味着我以后可以用emacs来记笔记，写博客。哈哈哈
*** 2017-12-12 Tuesday

**** game is life 
i restart to play game which i uninstalled about half month ago.after two hours' 
relaxing,i feel tired and scared.cause i think i get addicted to the game again.
But i have to control my time spent on playing games.
*** 2017-12-14 Thursday

**** day 01  
The picture vividly depicts a lovely American girl in traditional Chinese costume 
with a sweet smile on her face.She wears ribbons necklaces and other accessories 
that are characteristic of the clothes of a certain Chinese minority group.
The fact that people from different countries are attached to mysterious Chinese
culture indicates that to some extent a culture can be accepted,respected,
appreciated and shared internationally.In other words,a nation's unique culture 
can become international through worldwide economic and cultural exchanges can 
effectively improve mutual understanding and friendship.
It's my view that national culture as priceless spiritual treasure should be 
preserved and cherished.Meanwhile,there are good reasons to advocate international
culture for these ideas from the other cultures,controversial or even absurd at 
first sight,can provide a different perspective for us to observe the world in the
long run.Nevertheless,when we are confronted with a different culture,we should be
sensible enough to absorb its essence and to resist its dark side.
*** 2017-12-15 Friday

**** day 02 
As is subtly portrayed in the cartoon,two tourists are taking sightseeing on a 
small boat while discarding their picnic leftovers casually into a lake.And below
the drawing,there is a topic which says:after the travel or me in the travel.
Form the portrayal,we can conclude that the painter wants to convey such a message:
a good many scenic spots are flooded with visitors,who spoil the beauty of nature
by creating and leaving God-knows-how-much trash.On the one hand,tourism,as a 
multi-billion-dollar business,is booming everywhere.On the other hand,tourism has 
exerted great pressure on the environment we are living in: water is polluted,the
ecological system is disturbed,and natural resources have been excessively used.
Undoubtedly,tourism could not be banned in any country as it does help to shore 
up the economy in places which offer few sources of income.The significant point
is that the unchecked growth of the travel business may render the development of
an economy unsustainable.
*** 2017-12-16 Saturday

**** day 03 
Nowadays,can we find a person who has not heard of online shopping?It maybe be a
little difficult.Online shopping is coming into fashion in most cities due to the 
rapid development of Internet technology.
Online shopping is welcomed by the majority of people owing to its obvious advantages:
it's convenient and people can do it 24-hour.You can shop whenever you want--if you 
want to buy mobile phone at 2 a.m.,you can.Unfortunately,shopping online has its own
disadvantages too:you can't touch the item,let alone try it on.The material of the
dress that you see on the screen may be flimsier than what you had expected,and item
will probably look much better on the model than it does on you.
Personally,i find buying online to be excellent way to shop to certain items.
Nevertheless,for the other items,such as clothes,i reckon it is better to shop at as
regular store.In a regular store,you can see the real color,feel the material,and 
try it on.
*** 2017-12-17 Sunday

**** day 04 
The diagram above clearly illustrates that dramatic elevation has occurred in the
recruitment of Master of Engineering in the past seven years.According to the 
statistics given above,we may conclude that the recruitment of ME was on a steady 
rise from 1998 to 2004.In 1998,the number was at a low level,only about 2500.
Surprisingly,it reached to more than 35000 in 2004 with in no more than seven years.
Some driving factors that contribute to the above-mentioned may be summarized as 
follows.First and foremost,China has become particularly active in manufacturing,
which leads to the increasing demand of qualified engineers.In addition,the 
development of job market on the whole cannot keep pace with the expansion of college
graduates,which obliges a large number of students to stay on campus for another
three years to get better prepared for their career.Last but not least,working 
pressure is another reason.Taking all these factors into account,we may predicate 
that with speedy development of our society,the number of recruitment of ME will
keep growing in the forthcoming decade.
On the other side of the coin,however,this tendency may bring about a good many 
problems,such as the waste of talent.It is necessary for us to take effective 
measures to ensure this situation doesn't get out of hand,and encourage students
to choose major in which theoretical knowledge and practical skills will be demanded
in the job market.
*** 2017-12-18 Monday

**** day 05 
The set of drawing above vividly depict the destiny of a flower in different 
circumstances.As is shown in the first cartoon,the flower is growing in full bloom 
in a comfortable greenhouse that shelters it from the threatening lighting and
storm.On the contrary,when removed from the greenhouse and exposed to the driving
rain,the flower soon fades and withers.
The delicate flower is naturally associated with young people,to be specific,the 
only children in our current society;the greenhouse epitomizes parents' doting 
care and abundant material supplies that can shield the children from the storm,or
the harsh reality.Once the young people begin to seek independence and accept 
challenges from the real world,they are found too spoiled to be strong enough in 
the face of difficulties.
Accordingly,it is vital for us to deprive positive implications from these thought-
provoking drawings.Only by undergoing more challenges and toils in adversity can 
young people cultivate strong personality and ability,and only in this way can they
become winners in this competitive world.
*** 2017-12-19 Tuesday

**** day 06 
As an old saying goes,"it takes years to build trust,and a few seconds to destroy 
it."Maintaining trust is the most important characteristic that a person requires
to be successful in life.Only by consistently proving to be honest can a person 
earn the precious trust of family members and business partners.
On the one hand,a parents' relationship  with his children must be based on trust
and integrity.If a father promises many times to take his son to a football match
and cancels every time,his son will naturally lose begin to lose faith in his 
parents' words.On the other hand,in the business world,people with no trust sooner
or later earn the bad reputation they deserve.I have observed how destructive a 
person's dishonesty has been to his chances for success,and how his relationship 
with other people are purely superficial,based only on self-interest.
Trust is a very valuable asset,which is easy to lose but hard to gain.In the long 
run,a honest person has earned the love and respect of the person closed to them,
which,in my opinion,is the greatest measure of a successful life.
*** 2017-12-20 Wednesday

**** day 07 
#+title: habit
There is saying that "good habits result from resisting temptation",to 
which i can't agree more.Unfortunately,lack of determined will and social
,teenagers frequently fall into the traps of temptations such as Internet 
games,smoking,drinking and so on.
In a bid to form good habits,one needs a strong will and perseverance to
resist temptation.Numerous examples can be given but these will suffice.
The outstanding habits of reading classic literature on a regular basis 
is a case in point.Nevertheless,you would definitely have to spend less 
time on your favorite Internet games or fascinating mobile phones.Likewise
,the good habit of doing exercising every day means repeatedly dragging
oneself from the TV series and cozy couch.These case effectively clarity 
that good habits arise from resisting temptation.
As has been mentioned above,a wise mind and determined will should be
gradually cultivated so that the adolescents can resist various bad 
temptations and form excellent habits.Just as Oscar Wilde,an esteemed 
Britain novelist put it,"I can resist everything except temptations".
 
