* 2017
** 2017-11 November
*** 2017-11-24 Friday

**** journal means travel diary or a plan? 
It is my fourth day from my learning spacemacs.I'm willing to finish this journal to record the my excellent mood.
The config of my spacemacs is due to zilongshanren.And i am hungry to config the spacemacs by myself in the future.
And this all for today's journal.
*** 2017-11-26 Sunday

**** summary after reinstall ubuntu16.04 
It is me who get myself in the trouble.I want to change my desktop to gnome in place of unity yesterday.I find it's very uncomfortable to
use gnome,so i decide to uninstall gnome desktop.To be honest,i want to purge all application about gnome.After i finish that,i find i can
start many applications such as uget,chrome.What's more,the icons in the bottom bar also disappeared quietly.All happned scared me,however
i don't how to solve this problem.So i have to reinstall all applications back.Then i reboot,but i can't log in my system anymore.Saddly,i
have to make a hard decision that is to reinstall ubuntu16.
*** 2017-11-27 Monday

**** I find a great application which is free and quick vpn.It is lantern.But the version 
i download from web is for ubuntu14,it's amazing to me that the version is valid in ubuntu16.
Althougth it just provides user with 500 M/month,it's is enough for me,emmmmm,this month.
*** 2017-11-29 Wednesday

**** start learn emacs lisp.And i have finished to 1.1:Lisp List.
** 2017-12 December
*** 2017-12-05 Tuesday

**** 正如你所看到的哈哈，今天贼鸡儿开心，因为终于知道怎么在神之编辑器中输入中文了，喂，好像哪里不对劲。
这逗号好像飘了。。。。还有句号。。。。算了管不了那么多了，哈哈哈，开心！！！
*** 2017-12-06 Wednesday

**** 学会在 emacs 下输入中文的第二天 
  感觉依然兴奋，依然开心。经过一番简单的测试，在emacs中启用外置搜狗输入法，虽然标点符号的显示位置有些问题，但基
本不影响日常使用。这个对我来说可以说是一个神技，意味着我以后可以用emacs来记笔记，写博客。哈哈哈
*** 2017-12-12 Tuesday

**** game is life 
i restart to play game which i uninstalled about half month ago.after two hours' 
relaxing,i feel tired and scared.cause i think i get addicted to the game again.
But i have to control my time spent on playing games.
*** 2017-12-14 Thursday

**** day 01  
The picture vividly depicts a lovely American girl in traditional Chinese costume 
with a sweet smile on her face.She wears ribbons necklaces and other accessories 
that are characteristic of the clothes of a certain Chinese minority group.
The fact that people from ifferent 

