* Quick notes

** happy hacking
*** the problem i met
About three days ago,i install the spacemacs and learn to use spacemacs.As you configure,i find spacemacs is very difficult to master in a short time.
So i plan to master spacemacs gradually in a long term.And i get some skills about org-agenda before long.So i decide to practice them in spacemacs.But
i met a problem:spacemacs reports a error about org-projectile when i finish todo items or quit.
*** the method i take 
Because spacemacs is quite unfamiliar to me,i hurry to ask for forum.But there is only one who answered afer a day.I do what he said but is not effective.
So i decide to figure it out in my own efforts.I look throught the doc and tutorials in spacemacs.Luckily,i locate the error where it takes place.I edit
the codes....I make it just now.And that is why i write this note.
*** the feelings now
I am very very happy.
  [2017-11-23 Thu 15:00]

** TODO [#C] update career.org 
  
  [[file:~/org-notes/career.org::*hacking%20spacemacs][hacking spacemacs]] 
  [2017-11-23 Thu 22:59]

** TODO [#C] add tips to use spacemacs better 
  
  [[file:~/org-notes/ubuntu.org::*enable/disable%20grammar%20check%20:space+t+S][enable/disable grammar check :space+t+S]] 
  [2017-11-23 Thu 23:06]

** TODO [#C] career org  
  
  [[file:~/org-notes/career.org::*hacking%20spacemacs][hacking spacemacs]] 
  [2017-11-24 Fri 09:00]

  
** TODO [#C] 
  %![Error: (void-function zilongshanren/retrieve-chrome-current-tab-url)]
 
  [2017-11-27 Mon 21:45]

** another error to correct 
if: Symbol’s function definition is void: org-projectile:capture-for-current-project
  
  [2017-11-27 Mon 22:14]

* Blog Ideas

** DONE [#B] not a idea but discover 
   CLOSED: [2017-11-24 Fri 12:02]
notes and ideas are in the same file in org-capture
  
  [2017-11-24 Fri 12:00]

