* Quick notes

** happy hacking
*** the problem i met
About three days ago,i install the spacemacs and learn to use spacemacs.As you configure,i find spacemacs is very difficult to master in a short time.
So i plan to master spacemacs gradually in a long term.And i get some skills about org-agenda before long.So i decide to practice them in spacemacs.But
i met a problem:spacemacs reports a error about org-projectile when i finish todo items or quit.
*** the method i take 
Because spacemacs is quite unfamiliar to me,i hurry to ask for forum.But there is only one who answered afer a day.I do what he said but is not effective.
So i decide to figure it out in my own efforts.I look throught the doc and tutorials in spacemacs.Luckily,i locate the error where it takes place.I edit
the codes....I make it just now.And that is why i write this note.
*** the feelings now
I am very very happy.
  [2017-11-23 Thu 15:00]

** DONE [#B] update career.org 
   CLOSED: [2017-11-29 Wed 17:59]
  
  [[file:~/org-notes/career.org::*hacking%20spacemacs][hacking spacemacs]] 
  [2017-11-23 Thu 22:59]

** DONE [#B] add tips to use spacemacs better 
   CLOSED: [2017-11-29 Wed 18:06] SCHEDULED: <2017-11-30 Thu>
   :PROPERTIES:
   :Effort:   1d
   :LAST_REPEAT: [2017-11-29 Wed 18:05]
   :END:
  
   - State "DONE"       from "TODO"       [2017-11-29 Wed 18:05]
  [[file:~/org-notes/ubuntu.org::*enable/disable%20grammar%20check%20:space+t+S][enable/disable grammar check :space+t+S]] 
  [2017-11-23 Thu 23:06]

** [#C] career org  
   :LOGBOOK:
   CLOCK: [2017-11-29 Wed 15:54]--[2017-11-29 Wed 15:54] =>  0:00
   :END:
  
  [[file:~/org-notes/career.org::*hacking%20spacemacs][hacking spacemacs]] 
  [2017-11-24 Fri 09:00]

** DONE another error to correct                                    :hacking:
   CLOSED: [2017-12-01 Fri 09:43] SCHEDULED: <2017-12-01 Fri 10:00>
if: Symbol’s function definition is void: org-projectile:capture-for-current-project
  
  [2017-11-27 Mon 22:14]

** DONE [#B] add link org-mode tutorials 
   CLOSED: [2017-11-29 Wed 16:38]
  http://v.youku.com/v_show/id_XMTM2MjM5OTU5Ng==.html?spm=a2h1n.8251843.playList.5!4~5~A&f=26137579&o=1
  [2017-11-29 Wed 15:25]

** DONE [#A] learn AHP layers analyse 
   CLOSED: [2017-11-29 Wed 19:10] SCHEDULED: <2017-11-29 Wed 19:00>
https://jingyan.baidu.com/article/cbf0e500eb95582eaa28932b.html

** TODO [#B] learn to write a blog 
   SCHEDULED: <2017-12-01 Fri>
http://blog.csdn.net/kesarchen/article/details/50579550
https://zilongshanren.com/blog/2015-07-19-add-org-mode-support.html
  [2017-11-29 Wed 17:51]

** TODO [#C] learn org mode and take notes about org mode agenda      :study:
   SCHEDULED: <2017-12-02 Sat 10:30 .+1d>
   :PROPERTIES:
   :LAST_REPEAT: [2017-12-01 Fri 11:16]
   :END:
  
   - State "DONE"       from "TODO"       [2017-12-01 Fri 11:16]
   - State "DONE"       from "TODO"       [2017-11-30 Thu 21:58]
   - State "DONE"       from "TODO"       [2017-11-29 Wed 18:47]
  [[file:~/org-notes/ubuntu.org::*enter%20"t"%20to%20change%20state(todo%20done)%20of%20task%20when%20your%20cursor%20is%20on%20task][enter "t" to change state(todo done) of task when your cursor is on task]] 
  [2017-11-29 Wed 18:04]

* Blog Ideas

** DONE [#B] not a idea but discover 
   CLOSED: [2017-11-24 Fri 12:02]
notes and ideas are in the same file in org-capture
  
  [2017-11-24 Fri 12:00]

